libc_a_SOURCES += \
	%D%/read.S %D%/write.S %D%/open.S %D%/close.S %D%/lseek.S \
	%D%/fstat.S %D%/stat.S %D%/isatty.S %D%/ioctl.S \
	%D%/link.S %D%/unlink.S %D%/kill.S %D%/wait.S %D%/getpid.S \
	%D%/fork.S %D%/execve.S \
	%D%/sbrk.S %D%/brk.S %D%/cerror.S %D%/exit.S
